#!/bin/sh
set -e

# source confmodule to ensure templates are loaded
. /usr/share/debconf/confmodule


# Automatically added by dh_python3
if which py3compile >/dev/null 2>&1; then
	py3compile -p etckeeper 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p etckeeper  || true
fi

# End automatically added section
# Automatically added by dh_installdeb/13
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/etckeeper 1.18.3-1\~ etckeeper -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'etckeeper.timer' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'etckeeper.timer'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'etckeeper.timer' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'etckeeper.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'etckeeper.service' 'etckeeper.timer' >/dev/null || true
	fi
fi
# End automatically added section


# Move a conffile without triggering a dpkg question
mv_conffile() {
	OLDCONFFILE="$1"
	NEWCONFFILE="$2"

	if [ -e "$OLDCONFFILE" ]; then
		echo "Preserving user changes to $NEWCONFFILE ..."
		mv -f "$NEWCONFFILE" "$NEWCONFFILE".dpkg-new
		mv -f "$OLDCONFFILE" "$NEWCONFFILE"
	fi
}

case "$1" in
configure)
	if dpkg --compare-versions "$2" le "0.7"; then
		if [ -d /etc/etckeeper/pre-apt.d ]; then
			mv_conffile "/etc/etckeeper/pre-apt.d/README" \
				"/etc/etckeeper/pre-install.d/README"
			mv_conffile "/etc/etckeeper/pre-apt.d/50uncommitted-changes" \
				"/etc/etckeeper/pre-install.d/50uncommitted-changes"
			rmdir --ignore-fail-on-non-empty /etc/etckeeper/pre-apt.d
		fi
		if [ -d /etc/etckeeper/post-apt.d ]; then
			mv_conffile "/etc/etckeeper/post-apt.d/README" \
				"/etc/etckeeper/post-install.d/README"
			mv_conffile "/etc/etckeeper/post-apt.d/10git-test" \
				"/etc/etckeeper/post-install.d/10vcs-test"
			mv_conffile "/etc/etckeeper/post-apt.d/30git-add" \
				"/etc/etckeeper/post-install.d/30git-add"
			mv_conffile "/etc/etckeeper/post-apt.d/40git-rm" \
				"/etc/etckeeper/post-install.d/40git-rm"
			mv_conffile "/etc/etckeeper/post-apt.d/50git-commit" \
				"/etc/etckeeper/post-install.d/50vcs-commit"
			rmdir --ignore-fail-on-non-empty /etc/etckeeper/post-apt.d
		fi
		mv_conffile "/etc/etckeeper/init.d/40git-init" \
			"/etc/etckeeper/init.d/40vcs-init"
		mv_conffile "/etc/etckeeper/init.d/50git-ignore" \
			"/etc/etckeeper/init.d/50vcs-ignore"
		mv_conffile "/etc/etckeeper/init.d/50git-perm" \
			"/etc/etckeeper/init.d/50vcs-perm"
		mv_conffile "/etc/etckeeper/init.d/50git-pre-commit-hook" \
			"/etc/etckeeper/init.d/50vcs-pre-commit-hook"
		mv_conffile "/etc/etckeeper/init.d/70git-add" \
			"/etc/etckeeper/init.d/70git-add"
	fi
	if dpkg --compare-versions "$2" le "0.10"; then
        	for c in 10vcs-test 30git-add 30hg-addremove 40git-rm; do
			mv_conffile "/etc/etckeeper/post-install.d/$c" \
				"/etc/etckeeper/commit.d/$c"

		done
	fi
	if dpkg --compare-versions "$2" le "0.13"; then
		mv_conffile "/etc/etckeeper/init.d/10restore-etckeeper" \
			"/etc/etckeeper/init.d/20restore-etckeeper"
		mv_conffile "/etc/etckeeper/init.d/20restore-metadata" \
			"/etc/etckeeper/init.d/10restore-metadata"
	fi
	if dpkg --compare-versions "$2" le "0.28"; then
		for c in commit.d/30darcs-add init.d/60darcs-deleted-symlinks; do
			if [ -e /etc/etckeeper/$c ]; then
				chmod +x /etc/etckeeper/$c
			fi
		done
	fi
	if dpkg --compare-versions "$2" le "0.61"; then
		# may be left over from a botched conffile removal
		rm -f /etc/etckeeper/commit.d/40git-rm.dpkg-dist
	fi

	if [ "$2" = "" ] && [ -e "/etc/etckeeper/etckeeper.conf" ]; then
		# Fresh install.
		. /etc/etckeeper/etckeeper.conf || true
		if [ -n "$VCS" ] && [ -x "`which $VCS 2>/dev/null`" ]; then
			if etckeeper init; then
				if ! etckeeper commit "Initial commit"; then
					echo "etckeeper commit failed; run it by hand" >&2
				fi
			else
				echo "etckeeper init failed; run it by hand" >&2
			fi
		else
			echo "etckeeper init not ran as $VCS is not installed" >&2
		fi
	fi

	# prints error and exits nonzero if the ignore file cannot be updated
	etckeeper update-ignore || true
esac
