#!/bin/sh
set -e

# Automatically added by dh_installsystemd/13
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'etckeeper.service' 'etckeeper.timer' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/13
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/etckeeper 1.18.3-1\~ etckeeper -- "$@"
# End automatically added section

# Automatically added by dh_python3
if which py3clean >/dev/null 2>&1; then
	py3clean -p etckeeper 
else
	dpkg -L etckeeper | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section


if [ "$1" = remove ]; then
	# In case etckeeper is being purged, stash away a copy of
	# the files purging will need.
	mkdir -p /var/cache/etckeeper/stash
	if [ -e /etc/etckeeper/etckeeper.conf ]; then
		cp -a /etc/etckeeper/etckeeper.conf /var/cache/etckeeper/stash
	fi
	if [ -d /etc/etckeeper/uninit.d ]; then
		cp -a /etc/etckeeper/uninit.d /var/cache/etckeeper/stash
	fi
	if [ -x /usr/bin/etckeeper ]; then
		cp -a /usr/bin/etckeeper /var/cache/etckeeper/stash
	fi
fi
